# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: breyta

before:
  hooks:
    - go test ./...

builds:
  - id: breyta-unix
    main: ./cmd/breyta
    binary: breyta
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/breyta/breyta-cli/internal/buildinfo.Version={{ .Version }}
      - -X github.com/breyta/breyta-cli/internal/buildinfo.Commit={{ .Commit }}
      - -X github.com/breyta/breyta-cli/internal/buildinfo.Date={{ .Date }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - id: breyta-windows
    main: ./cmd/breyta
    binary: breyta
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/breyta/breyta-cli/internal/buildinfo.Version={{ .Version }}
      - -X github.com/breyta/breyta-cli/internal/buildinfo.Commit={{ .Commit }}
      - -X github.com/breyta/breyta-cli/internal/buildinfo.Date={{ .Date }}
    goos:
      - windows
    goarch:
      - amd64

archives:
  - id: unix
    builds:
      - breyta-unix
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - src: tools/parinfer-rust/{{ .Os }}/{{ .Arch }}/parinfer-rust
        dst: parinfer-rust
  - id: windows
    builds:
      - breyta-windows
    format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - src: tools/parinfer-rust/windows/amd64/parinfer-rust.exe
        dst: parinfer-rust.exe

checksum:
  name_template: checksums.txt

release:
  prerelease: auto

brews:
  - name: breyta
    ids:
      - unix
    repository:
      owner: breyta
      name: homebrew-tap
      branch: main
    directory: Formula
    homepage: https://flows.breyta.ai
    description: "Breyta CLI + TUI for working with flows"
    install: |
      bin.install "breyta"
      bin.install "parinfer-rust"
    test: |
      system "#{bin}/breyta", "version"
    commit_author:
      name: breyta-ci
      email: github-actions@breyta.ai
